### PR TITLE
Competition

### PR DESCRIPTION
**Pull request by GloryBoyK**
Final Commit - We need to merge this in all together as a team to close off this season

### CODE REVIEW

**Review by alexru26 — APPROVED** [review]
Thanks for season.

**Review by 27moorev — APPROVED** [review]
i didnt really do anything but good job

**Review by nataliemcwhorter — APPROVED** [review]
Good job everybody

**Review by Ryan-Bauroth — APPROVED** [review]
to the next one 🎉

**Review by PrestonSwigart — APPROVED** [review]
its been a pleasure, we go to worlds next year trust

**Comment by dbstjrgus** [comment]
thank you >.<

**Comment by tslom** [comment]
Locking in for next year

**Review by tslom — APPROVED** [review]

**Review by okCookie — COMMENTED** [review]
Good season

**Review by okCookie — APPROVED** [review]
Good season (forgot to press approve)

**Review by a1cd — APPROVED** [review]

**Comment by GloryBoyK** [comment]
Alright guys, thanks for everything, and Everett - thanks for your 4 years, you gave us a lot.

**Pull request merged**
